### ISSUE TITLE
tui feedback in a light terminal

### ISSUE THREAD

**Issue by jellevandenhooff** [amonks/run#130]
An image says more than a thousand words:
<img width="1112" alt="image" src="https://github.com/amonks/run/assets/295724/70dfc9cf-3ad0-4824-9936-7f5bcf1b0f74">
That's a lot of yellow!

Also, I wish the `@watch` didn't blink. It's nice to know that `run` is still working, but the blinking is distracting.

**Comment by cgsdev0** [comment]
@jellevandenhooff which terminal is this? this looks very busted

**Comment by amonks** [comment]
what's your $TERM?

**Comment by amonks** [comment]
I can repro! thanks.

I imagine we're using some ansi sequence that Terminal.app doesn't support properly.

In the meantime, `TERM=screen run ...` (which disables some features) might look marginally better, depending on your color scheme.

**Comment by amonks** [comment]
@jellevandenhooff here's a branch that disables color entirely, in case that's helpful before there's a real fix: `amonks/no-color`

**Comment by amonks** [comment]
fixed in v1.0.0-beta.30

thanks again @jellevandenhooff for the report

**Comment by amonks** [comment]
I get 30 when I install @latest _now_, so perhaps installing it explicitly busted the cache.

_later..._

yeah, based on the docs here https://index.golang.org/#faq-new-version, it looks like updates take an unspecified amount of time to show up, but you can force them by go getting the new version explicitly. I'll add this to the release script (#137).

Thanks for reporting this!
