### ISSUE TITLE
Logs cropping in TUI mode

### ISSUE THREAD

**Issue by wagslane** [amonks/run#141]
It seems that if lines are too long they just get cropped, which is unfortunate. It would be nice if they wrapped around so that information in the logs isn't lost (or you have to do weird things like zoom waaaay out to see em.

You can see in the screenshot below that the word "version" is getting cut off. Afaik the only way to see it is to zoom out/enlarge the terminal.

![Screenshot 2024-05-17 at 9 11 01 AM](https://github.com/amonks/run/assets/21992789/7b9f332d-b56a-40e5-b4a0-1b5ce70932ca)

Terminal: VS Code Integrated
OS: Mac OS (M1 apple silicon)
Mode: TUI

(if this issue is approved @cgsdev0 you can certainly help work on it if you'd like)

**Comment by cgsdev0** [comment]
you gotta press W to turn on line wrapping 

its kinda confusing i agree

**Comment by amonks** [comment]
closing as works-as-designed, but please feel free to open another issue if hitting `w` doesn't get you sorted :)

thanks @cgsdev0 for running support
