### ISSUE TITLE
installing with go

### ISSUE THREAD

**Issue by cgsdev0** [amonks/run#30]
I ran the following command from the README:

```
go install github.com/amonks/run@latest
```

I get this error using go 1.20.6:

```
package github.com/amonks/run is not a main package
```

this, however, did work for me:
```
go install github.com/amonks/run/cmd/run@latest
```

i'm a bit foggy on how go modules work, so I'm not sure if this is a me problem or an issue with the instructions in the README 😅

**Comment by amonks** [comment]
oh! you're right; great catch.

fixed the readme in #33 👍
