### ISSUE TITLE
bug: setting env vars on task overwrites existing env

### ISSUE THREAD

**Issue by ecshreve** [amonks/run#76]
i'm seeing some strange behavior when trying to set env vars on a task, pushed a branch with the example tasks referenced below: https://github.com/amonks/run/compare/main...ecshreve:run:ecs/env-bug

tldr: i tried a few different things. and the only way im able to set an env var via the field on the task and have it persist in the task, results in the rest of my `env` disappearing

tasks:
```
[[task]]
  id = "simple"
  type = "short"
  cmd = """
    echo "hello world"
    echo "TESTENV: $TESTENV"
    env | head -n 10
    echo "done"
  """

[[task]]
  id = "simple-env"
  type = "short"
  env = { TESTENV="test" }
  cmd = """
    echo "hello world"
    echo "TESTENV: $TESTENV"
    env | head -n 10
    echo "done"
  """

[[task]]
  id = "simple-env-two"
  type = "short"
  env = [{ TESTENV="test" }]
  cmd = """
    echo "hello world"
    echo "TESTENV: $TESTENV"
    env
    echo "done"
  """
```

testing:
```
> run simple > run.log
> run simple-env >> run.log
> run simple-env-two >> run.log

> cat run.log
  simple  starting
          hello world
          TESTENV: 
          NVM_INC=/Users/eric/.nvm/versions/node/v16.16.0/include/node
          TERM_PROGRAM=vscode
          ABBR_TIPS_PROMPT=\n💡 \e[1m{{ .abbr }}\e[0m => {{ .cmd }}
          NVM_CD_FLAGS=
          SHELL=/opt/local/bin/fish
          TERM=xterm-256color
          FORGIT_INSTALL_DIR=/Users/eric/.config/fish/conf.d
          fzf_history_opts=--preview-window=top:4:wrap
          TMPDIR=/var/folders/m4/w2m5tqm924vg6l09py6zxld40000gn/T/
          TERM_PROGRAM_VERSION=1.81.0-insider
          done
          exit ok

     run  done
  simple-env  starting
              hello world
              TESTENV: test
              PWD=/Users/eric/github.com/run/example
              SHLVL=1
              TESTENV=test
              _=/usr/bin/env
              done
              exit ok

         run  done
  simple-env-two  starting
                  hello world
                  TESTENV: 
                  NVM_INC=/Users/eric/.nvm/versions/node/v16.16.0/include/node
                  TERM_PROGRAM=vscode
                  ABBR_TIPS_PROMPT=\n💡 \e[1m{{ .abbr }}\e[0m => {{ .cmd }}
                  NVM_CD_FLAGS=
                  SHELL=/opt/local/bin/fish
                  TERM=xterm-256color
                  FORGIT_INSTALL_DIR=/Users/eric/.config/fish/conf.d
                  fzf_history_opts=--preview-window=top:4:wrap
                  TMPDIR=/var/folders/m4/w2m5tqm924vg6l09py6zxld40000gn/T/
                  TERM_PROGRAM_VERSION=1.81.0-insider
                  done
                  exit ok

             run  done
```

**Comment by ecshreve** [comment]
okay, i think this is happening because of how [`os.Exec.Cmd` handles `Env` ](https://pkg.go.dev/os/exec#Cmd.Env), specifically: 
```	
// Env specifies the environment of the process.
// Each entry is of the form "key=value".
// If Env is nil, the new process uses the current process's
// environment.
```

When nothing is provided in the task for `env`, and we do `t.cmd.Env = t.env` in `func (t *scriptTask) startCmd()`, `t.cmd.Env` remains `nil` when we call `Cmd.Start()`, and uses the current environment. 

When a value is provided in the task in the form `env = { SOME_VAR = "some var value" }`,  `t.cmd.Env` is assigned only the values provided, and does not attempt to copy or merge with the existing environment.

I think we can append to the existing environment by doing something along these lines: https://pkg.go.dev/os/exec#example-Command-Environment

**Comment by ecshreve** [comment]
@amonks I _think_ this change makes sense, but I'm not super confident because my dev setup does some passing around of environment variables for git/ssh/shell configuration. 

motivation is a situation like this: https://github.com/ecshreve/dndgen/blob/c5055fb3a7607791986e1fc4773650e1f9c4cc08/tasks.toml#L102

What I'm wanting to do is set default values in a `.env` file, and use the `[task.env]` field to selectively override some defaults on some tasks, rather than providing command line args in each task. There's surely a different way to handle all that, but it was what got me digging, very fun to investigate though

**Comment by amonks** [comment]
this makes perfect sense to me

I agree that we should apply env overrides on top of existing env, rather than replacing it

**Comment by ecshreve** [comment]
okay great, i'll clean this branch up a bit this week and toss a little cleaner of a pr up next week sometime. 💕

**Comment by amonks** [comment]
fyi @ecshreve: @cgsdev0 took this over and merged :)
