### ISSUE TITLE
one-line install

### ISSUE THREAD

**Issue by amonks** [amonks/run#94]
can we make a cross-platform one liner that installs the latest run version?

one approach would be curl|bash

is there a Universally Correct bin folder to put things in? seems to vary by distro/package-manager, but maybe there is a convention. Maybe ppl end up needing install scripts because they try to detect this.

**Comment by amonks** [comment]
Surveying some install scripts in the wild, here is a list of goals/priorities they have:
- **automatic**: small number of manual steps
- **noninvasive**: small number of changes to system (eg: put the program in the existing bin folder that the system already uses, vs put the program in a new folder and ask the user to configure their shell(s) for it)
- **auditable**: install script that is not scary for security-conscious users
- **reliable**: install script that works on every system
- **easy**: low effort from the publisher (the counterexample is tailscale, which collaborated with every distro and package manager to get their program added)

Here's a survey:
- fly.io, deno
  - install scripts:
    - https://fly.io/install.sh
    - https://deno.land/x/install@v0.1.9/install.sh?source=
  - path handling:
    - makes a new folder ~/{.fly,.deno}/bin
    - checks your shell to identify its configuration file
    - prints "add ~/{.fly,.deno}/bin to $SHELL_CONFIGURATION_FILE" and then an example `export` line
  - goals:
    - **automatic**: no; requires manual steps to change shell configuration
    - **noninvasive**: no; puts the binary in a weird new place; requires specific shell configuration
    - **auditable**: yes; the script even says in a comment that this is the goal
    - **reliable**: yes
    - **easy**: yes
- homebrew
  - install script: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  - path handling:
    - makes a new folder /usr/local/bin
    - has a "brew shellenv" command that checks your shell and prints a bunch of exports
    - recommends running `/usr/local/bin/brew shellenv >> $SHELL_CONFIGURATION_FILE`
  - goals:
    - **automatic**: no; requires manual steps to change shell configuration
    - **noninvasive**: no; puts the binary in a weird new place; requires specific shell configuration
    - **auditable**: no; the script is super hairy -and- depends on code from other files
    - **reliable**: meh; I mean we've all had homebrew issues (I switched to macports!), but at least it's _supposed to_ work on all systems
    - **easy**: yes
- tailscale
  - install script: https://tailscale.com/install.sh
  - path handling:
    - detects which package manager your OS uses, then uses that to install tailscale
    - (requires presence in a wide range of package managers)
  - goals:
    - **automatic**: yes
    - **noninvasive**: yes; collaborates with OS and package manager mainatiners to _ensure_ the files go in the normal places
    - **auditable**: yes; the script is long but it's a big readable case/switch, and the branches are short and obvious
    - **reliable**: yes, provided you use one of the (vast array of) systems they've worked to support
    - **easy**: heck no; basically intractible
- jpillora/installer
  - this project generates install scripts for arbitrary github repos
  - here's the one for amonks/run: https://i.jpillora.com/amonks/run!?type=script
  - path handling:
    - puts the binary into /usr/local/bin, and fails if that folder doesn't exist
    - if you use macports (or otherwise don't have /usr/local/bin on path) sucks to suck i guess glhf lmao
  - goals:
    - **automatic**: yes
    - **noninvasive**: meh; if you have /usr/local/bin it is _probably_ the normal place you put binaries, but it might not be
    - **auditable**: no; it generates scripts on demand; anything could be in there
    - **reliable**: no; only works if you have /usr/local/bin
    - **easy**: yes
- manually install from github (run, currently)
  - install script:
    - click on releases page
    - click into correct release
    - manually untar
    - mv to desired location
  - goals:
    - **automatic**: no; the least automatic
    - **noninvasive**: yes
    - **auditable**: yes
    - **reliable**: yes
    - **easy**: yes

Here's the "goals" sections as a table (fire is extra-bad):

| name               | automatic          | noninvasive        | auditable          | reliable           | easy               |
| ------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------ |
| fly.io, deno       | :red_circle:       | :fire:             | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| homebrew           | :red_circle:       | :red_circle:       | :red_circle:       | :warning:          | :white_check_mark: |
| tailscale          | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :fire:             |
| jpillora/installer | :white_check_mark: | :warning:          | :fire:             | :fire:             | :white_check_mark: |
| download manually  | :fire:             | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |

The only category we're bad on is "automatic", and the only approaches that are
good on "automatic" fail dramatically in other ways. This suggests an approach
where we reach an acceptable level of automaticness (fly's or homebrews: run
this script and then do one action) without their compromises:

I think the script should _just download the right binary to the working
directory_, then ask the user to put it wherever they like (or run it where it
lays)

**Comment by ecshreve** [comment]
this all makes sense to me and definitely tracks with my experience with one line install scripts in the past will take another pass at my PR with all of this in mind. Thanks so so much for writing that out!

**Comment by ecshreve** [comment]
Okay did a little more reading and a little more thinking. Looking at the common goals of install scripts, with a guidepost of "download the correct binary to the working directory", and put together a new draft of an install.sh script.

I think this is more on the right track now. Would love to hear your thoughts!

## New install script

```sh
#!/bin/sh

# This script downloads the latest release of run from GitHub and installs it 
# to the current directory.

set -e          # Exit immediately if a command fails
set -o pipefail # Fail a pipeline if any command fails

# Print an error message before exiting.
trap 'echo "Error: $0:$LINENO -- installation failed"' ERR 

# Determine the download URL for the current operating system and architecture.
TARGET_ASSET="run_$(uname)_$(arch).tar.gz"
DOWNLOAD_URL="https://github.com/amonks/run/releases/latest/download/${TARGET_ASSET}"

# Attempt the download and extraction. Suppress error output from curl and tar.
curl -fsSL $DOWNLOAD_URL 2>/dev/null | tar -xz run 2>/dev/null

echo "Installed run to $(pwd)/run"
```

## Analysis

### Summary

Why is this script good? _(imo)_

- For a user it's just as easy or easier to use than the existing installation methods.
- For maintainers it's easy to read, understand, and update; it should require minimal changes to keep it up-to-date.
- It aligns fairly well with the goals identified in other install scripts.

Why is this script bad? _(imo)_

- It relies on string interpolation to determine the download URL, which could be brittle if the URL pattern changes.
- It only works with the latest release, and does not provide any options for the user.

What could be improved?

- Add more error handling and feedback for the user. (ie check for the presence of required commands)
- Add configuration options for the user. (ie specify a version, specify an installation directory)

---

### Goal Breakdown

**automatic**
- Determines the download URL based on the user's system
- Does not require user input

**noninvasive**
- Does not modify the user's environment or system configuration
- Does not require root access

**auditable**
- Short and easy to read, no unnecessary complexity
- Uses common commands and patterns
  
**reliable**
- This script should work on unix-like systems (Linux, MacOS) with `curl` and `tar` installed
- Should be easy to introduce a Github action to check that the script works as expected in CI
  
**easy**
- Minimal changes should be required to keep the script up-to-date (ie if the download URL pattern changes, or if the behavior that redirects reqs to the /releases/latest to the actual release location changes)
- Straightforward to add functionality or options in the future

## Appendix

### Add section to README

> ### Install Script (MacOS, Linux)
> 
> Download and install the latest version of `run` to the current working directory.
> 
> ```sh
> curl -L https://raw.githubusercontent.com/amonks/run/main/install.sh | sh
> ```
>

### Reference
- https://josh-ops.com/posts/github-download-latest-release/

**Comment by amonks** [comment]
I absolutely love this; 10/10 would merge.

The "latest" download url is a great find; I definitely have some scripts I can simplify with that.

There are three changes I would make:

I fell down a rabbit hole last night reading mid-2010s blog posts for and against curl|bash. One thing that came up a lot is, if the `curl` fails partway through, bash can get a dangerous partial script. The example people give is a script that has, like, `rm -rf /tmp/something` and the download cuts off at `rm -rf /`. I don't see any particularly dangerous cut points in the script you've written (the pipe into tar is particularly clever), but still: the general fix is to wrap the whole script in a function and call it on the last line.

Second, I'd check for an existing file called ./run and error if we'd clobber it. (Maybe tar does this already? If so, ignore this suggestion.)

Finally, I'd add just a bit more text to the print at the end. Something like,

    Installed Run (v1.2.3 Darwin AMD64) to ./run
    Launch it from here or move it onto your $PATH.

**Comment by ecshreve** [comment]
Great! thanks so much ill PR it with those changes. I think the fly.io script wraps everything and does a check for existing executable. Thats the one I referenced most when putting this smol script together.

That is an interesting note on the `curl|bash` failure scenario, wrapping everything in a `main` and calling it at the end seems easy enough.

**Comment by ecshreve** [comment]
i made an oops in the readme :) #111
