### ISSUE TITLE
tui looks incredibly broken on terminals with bad color support

### ISSUE THREAD

**Issue by amonks** [amonks/run#99]
eg Terminal.app, which would be good to support

**Comment by amonks** [comment]
https://github.com/charmbracelet/lipgloss?tab=readme-ov-file#complete-adaptive-colors

TODO: 
- [ ] add colors file; use, like, intentionally chosen colors instead of just hex codes I happen to remember; maybe take from solarized or smth
- [ ] use those colors everywhere

**Comment by cgsdev0** [comment]
if you want a simple solution, you can just stick to only using ANSI colors

(these are the ones that are generally controlled by your terminal's theme)

**Comment by amonks** [comment]
the problem is stupider than that: i have tmux configured to report that it supports true color, and I was testing terminal.app _in tmux_, so we would send unsupported ansi codes and everything would get all fucky


turns out run works fine in terminal.app if it reports itself correctly!
